# Generated by Django 3.2.12 on 2024-09-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPFForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permanent_address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('marital_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permanent_address', models.TextField()),
                ('aadhar_no', models.CharField(max_length=12)),
                ('relationship', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpf_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='gpf.gpfform')),
            ],
        ),
    ]
